### ISSUE TITLE
i have some problem!

### ISSUE THREAD

**Issue by For-me** [davidmz/apng-canvas#10]
Hello,when i write this to do my work. I find it doesn't work.
JS and apng is successful introduction,but it not work.
console reminds me error:"http://www.xxxx.com/undefined"!
so,what happend?

**Comment by davidmz** [comment]
Sorry, I did not understand. Could you describe your problem in detail?

**Comment by For-me** [comment]
sorry,i solve this problem! it's my mistake.Thanks!
