### ISSUE TITLE
Not working on android webview

### ISSUE THREAD

**Issue by SemonCat** [davidmz/apng-canvas#16]
Hi,

I use this library on android webview,

but It's not working and no error message,

any idea?

**Comment by Ntropy** [comment]
Try to enable remote debugging through Google Chrome ( https://developers.google.com/web/tools/chrome-devtools/debug/remote-debugging/webviews#configure-webviews-for-debugging ) and you an see javascript error and find out what is working wrong.

**Comment by SemonCat** [comment]
Yes, I tried,

But no any error show and image just not working.
