### ISSUE TITLE
Animation disappears

### ISSUE THREAD

**Issue by hongchengfhc** [davidmz/apng-canvas#22]
When the apng of an acyclic animation is used, there is no problem with the first loading, and then the animation with < img > appended disappears
`function addImg() {
var imgD = new Image();
imgD.src = ""
document.body.appendChild(imgD)

}

setInterval(function() {
    addImg();
}, 3000)
`

**Comment by davidmz** [comment]
Could you provide the minimal example code on codepen.io or on similar service?

**Comment by hongchengfhc** [comment]
Oh, I found out it was my own problem. I'm sorry.
