### ISSUE TITLE
Images only animate first time

### ISSUE THREAD

**Issue by Gunderak** [davidmz/apng-canvas#6]
Works great on desktop but on Android Chrome the images only animate once, if you refresh they are static images.
Any ideas?

**Comment by davidmz** [comment]
I can not reproduce it. On both my Androids (Nexus 5 and 10) all works well.

But "traffic compression" option in Chrome disables animation because of transcoding images by Google's proxy. "Compressed" images is not APNG images anymore. May be that is your case?

**Comment by Gunderak** [comment]
It's now working perfectly thankyou and sorry for the confusion!
