### ISSUE TITLE
Not working on local machine with file://

### ISSUE THREAD

**Issue by grzesir** [davidmz/apng-canvas#8]
I'm having an issue running this on my local machine from files (getting CORS issues). You wrote that this is a known issue but I need it to work nonetheless. Any idea how to get this work on my local machine with Chrome WITHOUT running a server just to add the Access-Control-Allow-Origin header? Is there a reason why the files are fetched using XHR instead of simply getting them from a path?

**Comment by davidmz** [comment]
Unfortunately, there is no standard way to fetch data from local files (via file:// protocol) in Chrome.
 
You can use command line flag for chrome.exe — “[--allow-file-access-from-files](http://www.chrome-allow-file-access-from-file.com/)”, but it will only work on your local machine.
